### ISSUE TITLE
android o null

### ISSUE THREAD

**Issue by iamwindow** [safetysystemtechnology/location-tracker-background#18]
java.lang.RuntimeException: Unable to stop service br.com.safety.locationlistenerhelper.core.LocationService@2cbedd7: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.gms.common.api.GoogleApiClient.isConnected()' on a null object reference
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3741)
        at android.app.ActivityThread.-wrap28(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1832)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7002)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.gms.common.api.GoogleApiClient.isConnected()' on a null object reference
        at br.com.safety.locationlistenerhelper.core.LocationService.stopLocationUpdates(LocationService.java:143)
        at br.com.safety.locationlistenerhelper.core.LocationService.onDestroy(LocationService.java:150)
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3723)
        at android.app.ActivityThread.-wrap28(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1832) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:7002) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by iamwindow** [comment]
galaxy 9
